### ISSUE TITLE
opening /dev/kvm twice?

### ISSUE THREAD

**Issue by il-steffen** [nyx-fuzz/QEMU-Nyx#1]
leftover from dell/kvm fallback?

https://github.com/nyx-fuzz/QEMU-Nyx/blob/18ad4753d35fedfc93d3b5b0d60ff773c200ee96/accel/kvm/kvm-all.c#L1923

**Comment by schumilo** [comment]
Fixed in f62ffff4b6b1a976817b904fe1128759acf15058.
Thanks!
