### ISSUE TITLE
parsing bug in -fast_vm_reload?

### ISSUE THREAD

**Issue by il-steffen** [nyx-fuzz/QEMU-Nyx#17]
I observed some parse error when adding Qemu options after -fast_vm_reload. Not sure if this is expected behavior or a bug in how -fast_vm_reload is parsed? I did not see any obvious issue in the code..

Adding -device before -fast-vm-reload works fine:
`qemu-system-x86_64 -enable-kvm -machine kAFL64-v1 -cpu kAFL64-Hypervisor-v1,+vmx -drive if=virtio,format=raw,file=/tmp/disk.qcow2 -fast_vm_reload path=/dev/shm/kafl/snapshot/,load=off`

Appending afterwards fails in cmdline parser:
`qemu-system-x86_64 -enable-kvm -machine kAFL64-v1 -cpu kAFL64-Hypervisor-v1,+vmx -fast_vm_reload path=/dev/shm/kafl/snapshot/,load=off -drive if=virtio,format=raw,file=/tmp/disk.qcow2`
qemu-system-x86_64: Invalid parameter 'if'

**Comment by il-steffen** [comment]
This is a known issue. Added a workaround in kAFL frontend.

**Comment by schumilo** [comment]
Unfortunately, I can no longer reproduce this bug with the latest build. Could you please double check that (maybe I'm just missing something), so we can close this issue?

Thank you :-)

**Comment by schumilo** [comment]
Never mind, I have completely missed that this bug has already been fixed by the following PR: https://github.com/nyx-fuzz/QEMU-Nyx/pull/8
