### ISSUE TITLE
leftover /dev/dell access

### ISSUE THREAD

**Issue by il-steffen** [nyx-fuzz/QEMU-Nyx#2]
I think this only triggers if more than one IP region is used..

https://github.com/nyx-fuzz/QEMU-Nyx/blob/18ad4753d35fedfc93d3b5b0d60ff773c200ee96/nyx/interface.c#L315

**Comment by schumilo** [comment]
Fixed in 47c17c5a21c1e225168677c32ee2a563dc8130d7.
Thanks!
