### ISSUE TITLE
Assertion `cpu->pt_mmap != (void*)0xFFFFFFFFFFFFFFFF' failed

### ISSUE THREAD

**Issue by parikhakshat** [nyx-fuzz/QEMU-Nyx#27]
I am using KVM-Nyx on Ubuntu 20.04 with a processor that supports intel-pt.
I was following the tutorial listed here: https://github.com/Kharos102/kAFL/blob/master/docs/windows_tutorial.md
Whenever I run this command,
```bash
/kAFL/qemu-5.0.0/x86_64-softmmu/qemu-system-x86_64 -machine q35 -enable-kvm -m 1024 -hda ./windows.qcow2 -cdrom ./windows.iso
```
the qemu binary crashes with the following error
```
qemu-system-x86_64: /home/blank/Downloads/kAFL/kafl/qemu/nyx/pt.c:326: pt_pre_kvm_run: Assertion `cpu->pt_mmap != (void*)0xFFFFFFFFFFFFFFFF' failed.
```
How should I fix this?

**Comment by schumilo** [comment]
Please make sure that your system is not running low on memory. Usually, this happens if KVM-Nyx is not able to allocate a specific amount of memory: 

https://github.com/nyx-fuzz/QEMU-Nyx/blob/qemu-nyx-4.2.0/nyx/pt.c#L325

Could you provide more information (CPU, other specs)? Has it worked before?

**Comment by parikhakshat** [comment]
QEMU was working yesterday night just before I restarted my computer. My CPU is intel i7-1255U. I have 32gb of ram, so I don't think memory would be an issue.

**Comment by schumilo** [comment]
Please check one more time if there are really no QEMU processes (or other programs) running in the background and occupying tons of physical memory (not virtual; `RES` in `htop`).

**Comment by parikhakshat** [comment]
Yeah, there really is nothing on my machine that is using memory except firefox. Firefox is only using like 2.1 gigabytes of memory.

**Comment by parikhakshat** [comment]
When I remove the argument -enable-kvm, qemu runs fine and the vm boots up.

**Comment by parikhakshat** [comment]
I just restarted my computer once again and qemu is working. Strange. Thanks for your help, nonetheless.

**Comment by il-steffen** [comment]
Recently ran into this again. It seems to when the system has some memory pressure, e.g. all RAM reserved for file cache.
Would be more helpful to check the return code and print errno here.
