### ISSUE TITLE
Unable to write to VM Disk

### ISSUE THREAD

**Issue by parikhakshat** [nyx-fuzz/QEMU-Nyx#28]
Hello,
I am facing a new problem when trying to create a windows 10 VM using qemu-nyx. 
My command to start the vm is as follows:
```
./kAFL/kafl/qemu/x86_64-softmmu/qemu-system-x86_64 -machine q35 -enable-kvm -m 4096 -hda ./windows.qcow2 -cdrom ./windows.iso -boot d
```
When the setup reaches to the page to select the partition, Windows says that it is unable to install the OS to the disk. Looking into the setup logs and output of diskpart, I can see that whenever Windows tries to write or modify the disk, it gives an error saying that this drive is write-protected.
How can I fix this issue?

Note: Whenever I use normal qemu with the exact same CLI arguments and disk, Windows is able to install to the disk with ease. This shows that the problem may lie in the nyx version of qemu

**Comment by schumilo** [comment]
Try to use `qemu_tool.sh` (https://github.com/nyx-fuzz/packer/blob/main/qemu_tool.sh#L83) for that or set `NYX_DISABLE_DIRTY_RING=y NYX_DISABLE_BLOCK_COW=TRUE` manually. Otherwise, the data is not written to the virtual HDD and some other artifacts may occur.
