### ISSUE TITLE
Unable to install any system on qemu-nyx

### ISSUE THREAD

**Issue by r3bb1t** [nyx-fuzz/QEMU-Nyx#3]
Latest version of QEMU-Nyx works, but doesn't allow to properly install system. 
Before building QEMU-Nyx i followed all the installation instructions from here https://github.com/nyx-fuzz/KVM-Nyx, then installed pkg-config, flex and bison via apt. After that i cloned the QEMU-Nyx repository, executed "./compile_qemu_nyx.sh lto" and after the building was done i added qemu-system-x86_64 to PATH (for conviniece)

The problem: 
After trying to install freebsd from https://github.com/RUB-SysSec/Nyx/tree/main/Targets/bhyve/VM i am getting error during the VM installation process. While installing on clean qemu-kvm (apt install qemu-kvm) i don't get any errors with the same parameters. Even when i managed to install the VM, i am returning back to the installer after reboot.

![qemu](https://user-images.githubusercontent.com/49586603/150805211-78a793b2-89be-4c39-80e8-313a821bfa84.png)

**Comment by schumilo** [comment]
Thanks for your bug report!
Could you please share some more information, like which Version of FreeBSD did you use and all steps to reproduce this issue.
I'll have a look at this in the next few days. 

By the way, there is no guarantee that the old setup scripts from the USENIX prototype are still compatible with this version of QEMU-Nyx. To properly install a full OS in Nyx, please use [qemu_tool.sh](https://github.com/nyx-fuzz/packer/blob/main/qemu_tool.sh) instead. 

You can also try setting the following environment variable before starting QEMU-Nyx for guest OS installation: `NYX_DISABLE_DIRTY_RING=y`.

**Comment by r3bb1t** [comment]
Thanks for fast response. 
Tommorow i am going to fully reset my server and reinstall the whole project. I will send you the bash script to reproduce the issue.

**Comment by r3bb1t** [comment]
It seems that i can't link the bash script here, so i have to write everything down here. So, what i did was:

apt install unzip -y
apt install git -y
apt install pkg-config -y
apt install flex bison -y
apt install gettext -y
apt install libgtk-3-dev -y

cd /tmp/ &&
wget -c https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.73/amd64/linux-image-unsigned-5.10.73-051073-generic_5.10.73-051073.202110131013_amd64.deb &&
wget -c https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.73/amd64/linux-modules-5.10.73-051073-generic_5.10.73-051073.202110131013_amd64.deb &&
sudo dpkg -i *.deb
sudo reboot

After the reboot i executed the following commands:

git clone --recursive https://github.com/nyx-fuzz/QEMU-Nyx/
cd QEMU-Nyx
./compile_qemu_nyx.sh lto
make install
apt install qemu-utils
cd


wget https://github.com/nyx-fuzz/KVM-Nyx/releases/download/v5.10.73/kvm-nyx-5.10.73-1.0.zip
unzip kvm-nyx-5.10.73-1.0.zip
cd kvm-nyx-5.10.73-1.0
sudo rmmod kvm_intel kvm
sudo insmod ./kvm.ko;
sudo insmod ./kvm-intel.ko;
sudo chmod 777 /dev/kvm

git clone https://github.com/RUB-SysSec/Nyx
cd Nyx/Targets/bhyve/VM/
sh prepare.sh


After that i connected to the vm via vnc and tried to install everything with default settings (basically hitting enter everywhere except the "set hostname tab".  Result - unsuccessful installation and it gets worse when accepting the system's offer to retry.

I can give acces to my server or provide any required info if needed. Thanks in advance


My server: 
Ubuntu 20.04 LTS x86_64
RAID1+LVM
I7 8700
32gb ddr4

P.s. Unfortunately, `NYX_DISABLE_DIRTY_RING=y` doesn't seem to help. 
P.p.s Can't get qemu_tool.sh to work as well

![Screenshot_20220125-222309](https://user-images.githubusercontent.com/49586603/151045188-9f651479-d7f3-4e3d-8caf-9b04ccfcc840.jpg)

**Comment by schumilo** [comment]
First of all, this version of QEMU-NYX doesn't support hypervisor fuzzing at all (support is somewhat broken; but I'll do my best to fix it, but please don't hold your breath -> it might take a while). 
So if your goal is to fuzz bhyve or another hypervisor, you should probably stick with the old USENIX release of Nyx.

But anyway, I've managed to successfully finish the OS installation of FreeBSD on my system. So it worked like a charm. But I've used `qemu_tool.sh` to install FreeBSD instead of the old prepare.sh script.

To get `qemu_tool.sh` running you need execute the following commands first: 

```
git clone git@github.com:nyx-fuzz/packer.git
cd packer/packer
./nyx_packer.py # this command will create a new nyx.ini file

# fix the path to the QEMU-Nyx executable in the nyx.ini file
vim nyx.ini

cd ../
./qemu_tool.sh # this should work now
```

To install FreeBSD with `qemu_tool.sh` you could simply run the following commands: 

```
# first, let's create an image (20GB) 
./packer/qemu_tool.sh create_image freebsd.img 20000

# now, start the FreeBSD installer and connect via VNC 
./packer/qemu_tool.sh install freebsd.img FreeBSD-11.3-RELEASE-amd64-disc1.iso
```

PS: If you want to fuzz anything other than hypervisors, check out the latest [Nyx integration in AFL++](https://github.com/AFLplusplus/AFLplusplus/tree/dev/nyx_mode).

![freebsd](https://user-images.githubusercontent.com/8689842/151058292-daae217b-a4ff-4153-af1d-3c6551805058.jpg)

**Comment by r3bb1t** [comment]
Huge thanks for the fast solution of my problem. Now i am able to install the VM's properly 👍. At this moment i don't have any questions left :)

P.s. IMHO it would be good to delete the german keyboard parameter `(-k de)` in bash scripts because it can confuse the people who are using this fuzzer for the first time.
P.p.s The project is really great, but it's still missing the important documentation.
