### ISSUE TITLE
finish the build, and how to continue to do the next work?

### ISSUE THREAD

**Issue by AURORA1325** [nyx-fuzz/QEMU-Nyx#55]
Hello ！ thank you very much for your work. It's amaizing. When I reproduced, I ran into some problems. Once I've done the `./compile_qemu_nyx.sh lto` build, how do I proceed with the fuzz test in qemu next ?

looking forward your reply

**Comment by schumilo** [comment]
QEMU-Nyx as is does only serve as the backend component of the entire framework. Right now, there are the following fuzzers which actually employ Nyx for fuzzing: 

- [AFL++ Nyx-Mode](https://github.com/AFLplusplus/AFLplusplus/tree/stable/nyx_mode)
- [kAFL](https://github.com/IntelLabs/kAFL)
- [Nyx-Net (enables fuzzing of network applications)](https://github.com/RUB-SysSec/nyx-net)
- [libAFL Nyx-Mode](https://aflplus.plus/libafl-book/advanced_features/nyx.html)
- [Nyx for hypervisor fuzzing (no longer maintained)](https://github.com/RUB-SysSec/Nyx)

In case you want to add Nyx support to your own fuzzer, you might find the following example useful: 

https://github.com/nyx-fuzz/libnyx/blob/main/libnyx/test.c#L64
